openapi: 3.0.0
info:
  title: Product Service API
  description: API for managing products
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get list of products
      operationId: getProductsList
      tags:
        - Products
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductStock'
        '500':
          description: Internal Server Error
    post:
      summary: Create new product
      operationId: createProduct
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                count:
                  type: integer
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Internal Server Error
  /products/{productId}:
    get:
      summary: Get product by ID
      operationId: getProductsById
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          description: ID of the product to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductStock'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal Server Error

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the product
        description:
          type: string
          description: Description of the product
        title:
          type: string
          description: Title of the product
        price:
          type: number
          description: Price of the product
    Stock:
      type: object
      properties:
        product_id:
          type: string
          format: uuid
          description: Unique identifier for the product
        count:
          type: number
          format: integer
          description: Number of products
    ProductStock:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the product
        description:
          type: string
          description: Description of the product
        title:
          type: string
          description: Title of the product
        price:
          type: number
          description: Price of the product
        count:
          type: number
          format: integer
          description: Number of products
