service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  environment:
      frontendURL: https://d2q2y64ixwkjjo.cloudfront.net

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: handler.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get

